// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnwsRp5tuL5XnMh4BgOIgw7HPAMvnnRfw',
    appId: '1:1004809312887:web:cb9172643084ef83938472',
    messagingSenderId: '1004809312887',
    projectId: 'my-app-c9ef9',
    authDomain: 'my-app-c9ef9.firebaseapp.com',
    storageBucket: 'my-app-c9ef9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLj7TZJ6JYTtfTHx4CIpwfVZd8MxjbYVU',
    appId: '1:1004809312887:android:006145b123648fba938472',
    messagingSenderId: '1004809312887',
    projectId: 'my-app-c9ef9',
    storageBucket: 'my-app-c9ef9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvLrWav7ljB1GXAAGYoadI4ul1ibp9418',
    appId: '1:1004809312887:ios:93d35908d9b751bd938472',
    messagingSenderId: '1004809312887',
    projectId: 'my-app-c9ef9',
    storageBucket: 'my-app-c9ef9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvLrWav7ljB1GXAAGYoadI4ul1ibp9418',
    appId: '1:1004809312887:ios:93d35908d9b751bd938472',
    messagingSenderId: '1004809312887',
    projectId: 'my-app-c9ef9',
    storageBucket: 'my-app-c9ef9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnwsRp5tuL5XnMh4BgOIgw7HPAMvnnRfw',
    appId: '1:1004809312887:web:9bba64dfb30d5cf1938472',
    messagingSenderId: '1004809312887',
    projectId: 'my-app-c9ef9',
    authDomain: 'my-app-c9ef9.firebaseapp.com',
    storageBucket: 'my-app-c9ef9.firebasestorage.app',
  );

}